"""Javni brand proizvoda. Interni kod, env i cookie ostaju sepko / SEPKO_*."""

DISPLAY_NAME = "ProRačun"
DISPLAY_ASCII = "ProRacun"
DOMAIN = "proracun.me"
SITE_URL = "https://proracun.me"
COMPANY_NAME = "Prostudio"
COMPANY_DOMAIN = "prostudio.me"
COMPANY_URL = "https://prostudio.me"
LICENSE_ITEM = "ProRačun Basic WEB"
MAIL_FROM_NAME = "ProRačun"
PWA_NAME = "ProRačun"
PWA_SHORT = "ProRačun"
POS_PWA_NAME = "ProRačun Kasa"
USER_AGENT = "ProRacun/0.1"
